"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { fetchFromAPI } from "@/lib/fetch"
import { Calendar, TrendingUp, TrendingDown, ArrowRight, Download, ExternalLink, Loader2, Info, X } from "lucide-react"

interface OutputRow { month: string; total_gst_collected: string; total_cgst: string; total_sgst: string; total_igst: string; total_invoiced: string; invoice_count: string }
interface ReconRow { month: string; total_received: string; gst_on_received: string; payment_count: string }
interface B2BRow { month: string; client_name: string | null; client_gstin: string | null; place_of_supply: string | null; taxable_value: string; cgst_amount: string; sgst_amount: string; igst_amount: string }
interface Purchase { id: string; vendor_name: string; invoice_date: string; amount: string; cgst: string; sgst: string; igst: string }

interface GSTReport {
  outputGST: OutputRow[]
  reconciledPayments: ReconRow[]
  b2bBreakdown: B2BRow[]
  summary: { totalOutputGST: number; totalReconciledGST: number; unreconciledGST: number; reconciledPercentage: number }
}

function fmt(v: string | number) {
  return `₹${Number(v).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}
function fmtMonth(d: string) {
  return new Date(d).toLocaleDateString("en-IN", { year: "numeric", month: "long" })
}

export function GSTReportView() {
  const currentYear = new Date().getFullYear()
  const [report, setReport] = useState<GSTReport | null>(null)
  const [purchases, setPurchases] = useState<Purchase[]>([])
  const [loading, setLoading] = useState(true)
  const [startDate, setStartDate] = useState(`${currentYear}-04-01`)
  const [endDate, setEndDate] = useState(`${currentYear}-03-31`)
  const [exporting, setExporting] = useState(false)
  const [igstNoteDismissed, setIgstNoteDismissed] = useState(true)

  useEffect(() => {
    setIgstNoteDismissed(localStorage.getItem("gst-igst-note-dismissed") === "1")
  }, [])

  const dismissIgstNote = () => {
    localStorage.setItem("gst-igst-note-dismissed", "1")
    setIgstNoteDismissed(true)
  }

  const fetchReport = async () => {
    setLoading(true)
    try {
      const [rpt, purList] = await Promise.all([
        fetchFromAPI(`/api/gst-report?startDate=${startDate}&endDate=${endDate}`),
        fetchFromAPI(`/api/purchases`),
      ])
      setReport(rpt)
      setPurchases(purList)
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchReport() }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const totalInputGST = purchases.reduce((s, p) => s + Number(p.cgst) + Number(p.sgst) + Number(p.igst), 0)
  const netGSTPayable = (report?.summary.totalOutputGST || 0) - totalInputGST

  const exportGSTR1 = () => {
    if (!report) return
    // GSTR-1 JSON structure accepted by GST portal for bulk upload — one row per
    // client × place-of-supply × month, using the real state each invoice was billed to.
    const gstr1 = {
      gstin: "", // Will be filled from profile
      fp: endDate.slice(0, 7).replace("-", ""), // MMYYYY
      b2b: report.b2bBreakdown.map((row) => ({
        pos: row.place_of_supply || "",
        typ: "Regular",
        sply_ty: Number(row.igst_amount) > 0 ? "INTER" : "INTRA",
        client_name: row.client_name,
        client_gstin: row.client_gstin,
        month: fmtMonth(row.month),
        txval: Number(row.taxable_value),
        cgst: Number(row.cgst_amount),
        sgst: Number(row.sgst_amount),
        igst: Number(row.igst_amount),
      })),
      _meta: { generated_at: new Date().toISOString(), invoice_count: report.outputGST.reduce((s, r) => s + Number(r.invoice_count), 0) },
    }
    const blob = new Blob([JSON.stringify(gstr1, null, 2)], { type: "application/json" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `GSTR1_${startDate}_${endDate}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportGSTR3B = () => {
    if (!report) return
    const gstr3b = {
      period: `${startDate} to ${endDate}`,
      output_gst: report.summary.totalOutputGST,
      input_gst_credit: totalInputGST,
      net_tax_payable: Math.max(0, netGSTPayable),
      tax_credit_excess: netGSTPayable < 0 ? Math.abs(netGSTPayable) : 0,
      _note: "Generated by InvoiceFlow — upload JSON to GST portal or use values to fill GSTR-3B manually.",
      _generated: new Date().toISOString(),
    }
    const blob = new Blob([JSON.stringify(gstr3b, null, 2)], { type: "application/json" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `GSTR3B_Summary_${startDate}_${endDate}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (loading) {
    return <div className="flex items-center justify-center py-16 gap-2 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" />Loading GST report…</div>
  }

  return (
    <div className="space-y-6">
      {/* Period selector */}
      <Card>
        <CardHeader><CardTitle className="flex items-center gap-2"><Calendar className="h-5 w-5" />Report Period</CardTitle></CardHeader>
        <CardContent>
          <div className="flex items-end gap-4 flex-wrap">
            <div className="space-y-1.5 flex-1 min-w-[140px]">
              <Label>Start Date</Label>
              <Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} />
            </div>
            <div className="space-y-1.5 flex-1 min-w-[140px]">
              <Label>End Date</Label>
              <Input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} />
            </div>
            <Button onClick={fetchReport}>Generate</Button>
          </div>
        </CardContent>
      </Card>

      {/* One-time note: IGST is now included in the totals below */}
      {!igstNoteDismissed && (
        <div className="flex items-start gap-2 rounded-lg border border-blue-200 bg-blue-50 dark:border-blue-900 dark:bg-blue-950/50 px-4 py-3 text-sm">
          <Info className="h-4 w-4 mt-0.5 shrink-0 text-blue-600 dark:text-blue-400" />
          <p className="flex-1 text-blue-800 dark:text-blue-200">
            Updated calculation — GST totals now correctly include IGST for inter-state invoices.
            If you have inter-state clients, the numbers below may be higher than before.
          </p>
          <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0 text-blue-600 dark:text-blue-400" onClick={dismissIgstNote}>
            <X className="h-3.5 w-3.5" />
          </Button>
        </div>
      )}

      {/* GSTR-3B Calculator */}
      <Card className="border-2 border-primary/20">
        <CardHeader>
          <CardTitle>GSTR-3B Summary — Net Tax Payable</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <div className="flex justify-between items-center py-2 border-b">
              <div className="flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-red-500" />
                <span className="text-sm font-medium">Output GST (from invoices)</span>
              </div>
              <span className="font-bold text-red-600">{fmt(report?.summary.totalOutputGST || 0)}</span>
            </div>
            <div className="flex justify-between items-center py-2 border-b">
              <div className="flex items-center gap-2">
                <TrendingDown className="h-4 w-4 text-green-500" />
                <span className="text-sm font-medium">Input GST Credit (from purchases)</span>
              </div>
              <span className="font-bold text-green-600">− {fmt(totalInputGST)}</span>
            </div>
            <div className="flex justify-between items-center py-3 rounded-lg bg-primary/5 px-4">
              <div className="flex items-center gap-2">
                <ArrowRight className="h-5 w-5 text-primary" />
                <span className="font-bold text-base">Net Tax Payable to Govt</span>
              </div>
              <span className={`text-xl font-bold ${netGSTPayable >= 0 ? "text-red-600" : "text-green-600"}`}>
                {netGSTPayable >= 0 ? fmt(netGSTPayable) : `Credit: ${fmt(Math.abs(netGSTPayable))}`}
              </span>
            </div>
          </div>

          <div className="flex gap-2 mt-4 flex-wrap">
            <Button variant="outline" onClick={exportGSTR3B}>
              <Download className="h-4 w-4 mr-2" />
              Export GSTR-3B JSON
            </Button>
            <Button variant="outline" onClick={exportGSTR1}>
              <Download className="h-4 w-4 mr-2" />
              Export GSTR-1 JSON
            </Button>
            <Button variant="outline" onClick={() => window.open("https://www.gst.gov.in", "_blank")}>
              <ExternalLink className="h-4 w-4 mr-2" />
              Open GST Portal
            </Button>
          </div>
          <p className="text-xs text-muted-foreground mt-2">
            The JSON files match the format accepted by the GST portal for bulk upload. You can also use the summary values to fill GSTR-3B manually.
          </p>
        </CardContent>
      </Card>

      {/* Summary Cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">Output GST</CardTitle></CardHeader>
          <CardContent>
            <p className="text-2xl font-bold text-red-600">{fmt(report?.summary.totalOutputGST || 0)}</p>
            <p className="text-xs text-muted-foreground">On {report?.outputGST.reduce((s, r) => s + Number(r.invoice_count), 0)} invoices</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">Input GST Credit</CardTitle></CardHeader>
          <CardContent>
            <p className="text-2xl font-bold text-green-600">{fmt(totalInputGST)}</p>
            <p className="text-xs text-muted-foreground">On {purchases.length} purchases</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">GST Received</CardTitle></CardHeader>
          <CardContent>
            <p className="text-2xl font-bold text-blue-600">{fmt(report?.summary.totalReconciledGST || 0)}</p>
            <p className="text-xs text-muted-foreground">Via reconciled payments</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">Collection Rate</CardTitle></CardHeader>
          <CardContent>
            <p className="text-2xl font-bold">{(report?.summary.reconciledPercentage || 0).toFixed(1)}%</p>
            <p className="text-xs text-muted-foreground">Of invoiced GST received</p>
          </CardContent>
        </Card>
      </div>

      {/* Monthly detail */}
      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader><CardTitle>Output GST — Monthly Breakdown</CardTitle></CardHeader>
          <CardContent>
            {!report?.outputGST.length ? (
              <p className="text-sm text-muted-foreground py-4">No invoices in this period.</p>
            ) : (
              <div className="space-y-3">
                {report.outputGST.map((row) => (
                  <div key={row.month} className="flex items-center justify-between pb-3 border-b last:border-0">
                    <div>
                      <p className="font-medium text-sm">{fmtMonth(row.month)}</p>
                      <p className="text-xs text-muted-foreground">{row.invoice_count} invoices · Invoiced: {fmt(row.total_invoiced)}</p>
                      <p className="text-xs text-muted-foreground">CGST: {fmt(row.total_cgst)} · SGST: {fmt(row.total_sgst)}</p>
                    </div>
                    <div className="text-right">
                      <p className="font-bold text-red-600">{fmt(row.total_gst_collected)}</p>
                      <p className="text-xs text-muted-foreground">total GST</p>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Input GST Credit — Purchases</CardTitle></CardHeader>
          <CardContent>
            {!purchases.length ? (
              <p className="text-sm text-muted-foreground py-4">No purchases logged. <a href="/dashboard/purchases" className="underline text-primary">Add purchases</a> to claim input credit.</p>
            ) : (
              <div className="space-y-3">
                {purchases.slice(0, 8).map((p) => (
                  <div key={p.id} className="flex items-center justify-between pb-3 border-b last:border-0">
                    <div>
                      <p className="font-medium text-sm">{p.vendor_name}</p>
                      <p className="text-xs text-muted-foreground">{new Date(p.invoice_date).toLocaleDateString("en-IN")} · {fmt(p.amount)} (excl.)</p>
                    </div>
                    <div className="text-right">
                      <p className="font-bold text-green-600">{fmt(Number(p.cgst) + Number(p.sgst) + Number(p.igst))}</p>
                      <Badge variant="outline" className="text-xs mt-0.5">input GST</Badge>
                    </div>
                  </div>
                ))}
                {purchases.length > 8 && <p className="text-xs text-muted-foreground text-center">+{purchases.length - 8} more — <a href="/dashboard/purchases" className="underline">view all</a></p>}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
