"use client"

import type React from "react"
import { useState, useEffect, useRef } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import {
  CheckCircle2, Clock, AlertTriangle, Upload, ExternalLink,
  ChevronDown, ChevronUp, FileText, Trash2, Loader2, RefreshCw,
} from "lucide-react"

// ─── Document type registry ───────────────────────────────────────────────────

interface DocMeta {
  label: string
  shortDesc: string
  frequency: "monthly" | "annual" | "one-time" | "per-payment"
  // Day of next month the doc is due (monthly only)
  dueDayOfNextMonth?: number
  portalSection: string
  portalUrl: string
  downloadSteps: string[]
  acceptedFormats: string
}

const DOC_REGISTRY: Record<string, DocMeta> = {
  gstr2b: {
    label: "GSTR-2B",
    shortDesc: "Auto-drafted ITC (Input Tax Credit) statement generated by the portal",
    frequency: "monthly",
    dueDayOfNextMonth: 14,
    portalSection: "Returns > GSTR-2B",
    portalUrl: "https://www.gst.gov.in/#!/gstr2b",
    downloadSteps: [
      "Log in to gst.gov.in with your username and password",
      "Go to Services → Returns → Returns Dashboard",
      "Select the financial year and return period (month)",
      "Click on 'GSTR-2B' tile",
      "Click 'Generate' if not already generated (auto-available after 14th)",
      "Click 'Download' → choose JSON or PDF",
      "Save the file and upload it here",
    ],
    acceptedFormats: "PDF or JSON",
  },
  gstr1: {
    label: "GSTR-1",
    shortDesc: "Outward supplies return — details of all sales invoices you issued",
    frequency: "monthly",
    dueDayOfNextMonth: 11,
    portalSection: "Returns > Filed Returns",
    portalUrl: "https://www.gst.gov.in/#!/gstr1",
    downloadSteps: [
      "Log in to gst.gov.in",
      "Go to Services → Returns → Returns Dashboard",
      "Select the financial year and tax period",
      "Click on 'GSTR-1' tile",
      "If filed: click 'View Filed GSTR-1' → Download PDF/JSON",
      "If not yet filed: fill and submit first, then download the acknowledgment",
      "Upload the downloaded file here",
    ],
    acceptedFormats: "PDF or JSON",
  },
  gstr3b: {
    label: "GSTR-3B",
    shortDesc: "Monthly summary return — net tax liability, ITC claimed, and tax paid",
    frequency: "monthly",
    dueDayOfNextMonth: 20,
    portalSection: "Returns > Filed Returns",
    portalUrl: "https://www.gst.gov.in/#!/gstr3b",
    downloadSteps: [
      "Log in to gst.gov.in",
      "Go to Services → Returns → Returns Dashboard",
      "Select the financial year and tax period",
      "Click on 'GSTR-3B' tile",
      "Click 'View Filed GSTR-3B' → Download acknowledgment receipt",
      "Download the PDF confirmation of filing",
      "Upload it here for your records",
    ],
    acceptedFormats: "PDF",
  },
  gstr9: {
    label: "GSTR-9",
    shortDesc: "Annual GST return — consolidated summary of all monthly returns for the year",
    frequency: "annual",
    portalSection: "Returns > Annual Return",
    portalUrl: "https://www.gst.gov.in/#!/gstr9",
    downloadSteps: [
      "Log in to gst.gov.in",
      "Go to Services → Returns → Annual Return",
      "Select the financial year",
      "Click on 'GSTR-9' tile",
      "If filed: download the filed return and acknowledgment",
      "If not filed: file before 31st December of the following financial year",
      "Upload the acknowledgment receipt here",
    ],
    acceptedFormats: "PDF or JSON",
  },
  reg_cert: {
    label: "GST Registration Certificate",
    shortDesc: "Proof of GST registration — required for business transactions and vendor onboarding",
    frequency: "one-time",
    portalSection: "My Profile → Download Certificate",
    portalUrl: "https://www.gst.gov.in/#!/viewprofile",
    downloadSteps: [
      "Log in to gst.gov.in",
      "Click on your username (top right) → My Profile",
      "Scroll down to 'Registration Certificate'",
      "Click 'Download' to get the signed GST RC (REG-06)",
      "Upload it here — this is a one-time document",
    ],
    acceptedFormats: "PDF",
  },
  challan: {
    label: "PMT-06 Payment Challan",
    shortDesc: "Tax payment receipt — proof of GST paid into the electronic cash ledger",
    frequency: "per-payment",
    portalSection: "Payments → Challans",
    portalUrl: "https://www.gst.gov.in/#!/payment",
    downloadSteps: [
      "Log in to gst.gov.in",
      "Go to Services → Payments → Challan History",
      "Find your payment by date or CPIN number",
      "Click on the challan → Download PDF",
      "Upload each payment challan here for record-keeping",
    ],
    acceptedFormats: "PDF",
  },
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getCurrentPeriod(): string {
  const now = new Date()
  const mm = String(now.getMonth() + 1).padStart(2, "0")
  const yyyy = now.getFullYear()
  return `${mm}${yyyy}`
}

function getDueDateForDoc(docType: string): string | null {
  const meta = DOC_REGISTRY[docType]
  if (!meta || !meta.dueDayOfNextMonth) return null
  const now = new Date()
  const nextMonth = new Date(now.getFullYear(), now.getMonth() + 1, meta.dueDayOfNextMonth)
  return nextMonth.toISOString().split("T")[0]
}

function daysUntil(dateStr: string): number {
  const due = new Date(dateStr)
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  return Math.ceil((due.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
}

function fmtDate(d: string) {
  return new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })
}

// ─── Status badge ─────────────────────────────────────────────────────────────

function StatusBadge({ status, dueDate }: { status: string; dueDate?: string | null }) {
  if (status === "uploaded") {
    return (
      <Badge className="gap-1 bg-green-100 text-green-800 border-green-200 dark:bg-green-950 dark:text-green-300">
        <CheckCircle2 className="h-3 w-3" /> Uploaded
      </Badge>
    )
  }
  if (status === "overdue") {
    return (
      <Badge variant="destructive" className="gap-1">
        <AlertTriangle className="h-3 w-3" /> Overdue
      </Badge>
    )
  }
  if (dueDate) {
    const days = daysUntil(dueDate)
    if (days <= 0) {
      return <Badge variant="destructive" className="gap-1"><AlertTriangle className="h-3 w-3" /> Overdue</Badge>
    }
    if (days <= 7) {
      return (
        <Badge className="gap-1 bg-amber-100 text-amber-800 border-amber-200 dark:bg-amber-950 dark:text-amber-300">
          <Clock className="h-3 w-3" /> Due in {days}d
        </Badge>
      )
    }
    return (
      <Badge variant="secondary" className="gap-1">
        <Clock className="h-3 w-3" /> Due {fmtDate(dueDate)}
      </Badge>
    )
  }
  return <Badge variant="outline">Pending</Badge>
}

// ─── Single document card ─────────────────────────────────────────────────────

interface GSTDoc {
  id: number
  doc_type: string
  period: string | null
  file_name: string
  file_url: string
  status: string
  due_date: string | null
  uploaded_at: string | null
}

interface DocCardProps {
  docType: string
  uploads: GSTDoc[]
  onUploaded: () => void
}

function DocCard({ docType, uploads, onUploaded }: DocCardProps) {
  const meta = DOC_REGISTRY[docType]
  const [showSteps, setShowSteps] = useState(false)
  const [isDragging, setIsDragging] = useState(false)
  const [isUploading, setIsUploading] = useState(false)
  const [isDeleting, setIsDeleting] = useState<number | null>(null)
  const [error, setError] = useState<string | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const latestUpload = uploads[0]
  const currentDue = getDueDateForDoc(docType)
  const currentPeriod = getCurrentPeriod()

  // Check if current period is already uploaded
  const currentUploaded = uploads.some(
    (u) => u.status === "uploaded" && (!currentPeriod || u.period === currentPeriod || meta.frequency === "one-time")
  )
  const displayStatus = currentUploaded ? "uploaded" : latestUpload?.status || "pending"

  const handleFile = async (file: File) => {
    setIsUploading(true)
    setError(null)
    try {
      const form = new FormData()
      form.append("file", file)
      form.append("doc_type", docType)
      if (meta.frequency === "monthly") form.append("period", currentPeriod)
      if (currentDue) form.append("due_date", currentDue)

      const res = await fetch("/api/gst/documents", { method: "POST", body: form })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || "Upload failed")
      onUploaded()
    } catch (e) {
      setError(e instanceof Error ? e.message : "Upload failed")
    } finally {
      setIsUploading(false)
    }
  }

  const handleDelete = async (id: number) => {
    setIsDeleting(id)
    try {
      const res = await fetch(`/api/gst/documents?id=${id}`, { method: "DELETE" })
      if (!res.ok) throw new Error("Delete failed")
      onUploaded()
    } catch (e) {
      setError(e instanceof Error ? e.message : "Delete failed")
    } finally {
      setIsDeleting(null)
    }
  }

  const onDrop = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
    const f = e.dataTransfer.files[0]
    if (f) handleFile(f)
  }

  return (
    <Card className={`transition-all ${displayStatus === "overdue" ? "border-red-300 dark:border-red-800" : displayStatus === "uploaded" ? "border-green-200 dark:border-green-900" : ""}`}>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className={`rounded-lg p-2 ${displayStatus === "uploaded" ? "bg-green-100 dark:bg-green-950" : displayStatus === "overdue" ? "bg-red-100 dark:bg-red-950" : "bg-muted"}`}>
              <FileText className={`h-5 w-5 ${displayStatus === "uploaded" ? "text-green-600" : displayStatus === "overdue" ? "text-red-600" : "text-muted-foreground"}`} />
            </div>
            <div>
              <CardTitle className="text-base">{meta.label}</CardTitle>
              <CardDescription className="text-xs mt-0.5">{meta.shortDesc}</CardDescription>
            </div>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <StatusBadge status={displayStatus} dueDate={currentDue} />
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-3 pt-0">
        {/* Portal link */}
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>Portal: <span className="font-medium text-foreground">{meta.portalSection}</span></span>
          <a href={meta.portalUrl} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-primary hover:underline font-medium">
            Open GST Portal <ExternalLink className="h-3 w-3" />
          </a>
        </div>

        {/* Accordion: download steps */}
        <button
          type="button"
          onClick={() => setShowSteps((p) => !p)}
          className="w-full flex items-center justify-between text-xs font-medium text-muted-foreground hover:text-foreground transition-colors py-1.5 border-t border-b"
        >
          <span>How to download from gst.gov.in</span>
          {showSteps ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
        </button>

        {showSteps && (
          <ol className="space-y-1.5 pl-4 list-decimal">
            {meta.downloadSteps.map((step, i) => (
              <li key={i} className="text-xs text-muted-foreground leading-relaxed">{step}</li>
            ))}
          </ol>
        )}

        {/* Upload zone */}
        <label
          onDragOver={(e) => { e.preventDefault(); setIsDragging(true) }}
          onDragLeave={() => setIsDragging(false)}
          onDrop={onDrop}
          className={`flex flex-col items-center justify-center gap-2 border-2 border-dashed rounded-lg p-4 cursor-pointer transition-colors
            ${isDragging ? "border-primary bg-primary/5" : "border-muted-foreground/25 hover:border-primary/50 hover:bg-muted/30"}`}
        >
          <input
            ref={fileInputRef}
            type="file"
            accept=".pdf,.json,.csv,.xls,.xlsx"
            className="hidden"
            onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f) }}
          />
          {isUploading ? (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" /> Uploading…
            </div>
          ) : (
            <>
              <Upload className="h-5 w-5 text-muted-foreground" />
              <span className="text-xs text-muted-foreground text-center">
                Drop {meta.acceptedFormats} here or <span className="text-primary font-medium">click to browse</span>
              </span>
            </>
          )}
        </label>

        {error && <p className="text-xs text-destructive">{error}</p>}

        {/* Previous uploads list */}
        {uploads.length > 0 && (
          <div className="space-y-1.5">
            <p className="text-xs font-medium text-muted-foreground">Uploaded files</p>
            {uploads.map((doc) => (
              <div key={doc.id} className="flex items-center justify-between gap-2 rounded-md bg-muted/40 px-3 py-2">
                <div className="flex items-center gap-2 min-w-0">
                  <FileText className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
                  <div className="min-w-0">
                    <p className="text-xs font-medium truncate">{doc.file_name}</p>
                    {doc.uploaded_at && (
                      <p className="text-xs text-muted-foreground">{fmtDate(doc.uploaded_at)} {doc.period ? `· ${doc.period}` : ""}</p>
                    )}
                  </div>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  {doc.file_url && (
                    <a href={doc.file_url} target="_blank" rel="noopener noreferrer">
                      <Button variant="ghost" size="icon" className="h-7 w-7">
                        <ExternalLink className="h-3.5 w-3.5" />
                      </Button>
                    </a>
                  )}
                  <Button
                    variant="ghost" size="icon"
                    className="h-7 w-7 text-destructive hover:text-destructive"
                    onClick={() => handleDelete(doc.id)}
                    disabled={isDeleting === doc.id}
                  >
                    {isDeleting === doc.id
                      ? <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      : <Trash2 className="h-3.5 w-3.5" />}
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// ─── Main checklist component ─────────────────────────────────────────────────

const DOC_ORDER = ["gstr2b", "gstr1", "gstr3b", "gstr9", "reg_cert", "challan"]

export function GSTDocumentChecklist() {
  const [docs, setDocs] = useState<GSTDoc[]>([])
  const [loading, setLoading] = useState(true)
  const [lastRefresh, setLastRefresh] = useState(new Date())

  const fetchDocs = async () => {
    setLoading(true)
    try {
      const res = await fetch("/api/gst/documents")
      const data = await res.json()
      setDocs(Array.isArray(data) ? data : [])
      setLastRefresh(new Date())
    } catch {
      setDocs([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchDocs() }, [])

  const uploadedCount = DOC_ORDER.filter((type) =>
    docs.some((d) => d.doc_type === type && d.status === "uploaded")
  ).length

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold tracking-tight">GST Document Checklist</h2>
          <p className="text-sm text-muted-foreground mt-0.5">
            Download each document from gst.gov.in and upload here for your records.
            <span className="ml-2 font-medium text-foreground">{uploadedCount}/{DOC_ORDER.length} documents complete</span>
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={fetchDocs} disabled={loading}>
          {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
        </Button>
      </div>

      {/* Progress bar */}
      <div className="w-full h-2 bg-muted rounded-full overflow-hidden">
        <div
          className="h-full bg-green-500 rounded-full transition-all duration-500"
          style={{ width: `${(uploadedCount / DOC_ORDER.length) * 100}%` }}
        />
      </div>

      {/* Document cards */}
      {loading ? (
        <div className="flex items-center justify-center py-12 gap-2 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin" /> Loading documents…
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {DOC_ORDER.map((docType) => (
            <DocCard
              key={docType}
              docType={docType}
              uploads={docs.filter((d) => d.doc_type === docType)}
              onUploaded={fetchDocs}
            />
          ))}
        </div>
      )}

      <p className="text-xs text-muted-foreground text-right">
        Last refreshed {lastRefresh.toLocaleTimeString("en-IN")}
      </p>
    </div>
  )
}
